### ISSUE TITLE
Error while running strategy script

### ISSUE THREAD

**Issue by dsimba** [arms22/flyerbots#1]
Hi there, thanks for this framework! I was trying an example with:

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

I got the error below:

(base) C:\Users\autom\Downloads\arms22\flyerbots>python mmbot.py
Traceback (most recent call last):
  File "mmbot.py", line 3, in <module>
    from flyerbots.strategy import Strategy
  File "C:\Users\autom\Downloads\arms22\flyerbots\flyerbots\strategy.py", line 66
    return self.exchange.fetch_balance(async=False)
                                           ^
SyntaxError: invalid syntax

Any clue on this? Thanks

**Comment by meetaco** [comment]
@dsimba 
'async' is reserved
try 'async_' or something
